// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MKUoOQ6C-9dxunC8sWDUNwbX5MtDIKw',
    appId: '1:940352167567:web:1609fd0f0fba7659599afa',
    messagingSenderId: '940352167567',
    projectId: 'justgoproject-71919',
    authDomain: 'justgoproject-71919.firebaseapp.com',
    storageBucket: 'justgoproject-71919.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKbCQ2C3eY_7_ZwhG8SoKk7GHZiCRxrM',
    appId: '1:940352167567:android:c514fa9fcdc83d6e599afa',
    messagingSenderId: '940352167567',
    projectId: 'justgoproject-71919',
    storageBucket: 'justgoproject-71919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0VA3KNRaAz0It3oQs00I4EQN8EnPEhb4',
    appId: '1:940352167567:ios:58783d2559e46a43599afa',
    messagingSenderId: '940352167567',
    projectId: 'justgoproject-71919',
    storageBucket: 'justgoproject-71919.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0VA3KNRaAz0It3oQs00I4EQN8EnPEhb4',
    appId: '1:940352167567:ios:7b102e6dce28ee42599afa',
    messagingSenderId: '940352167567',
    projectId: 'justgoproject-71919',
    storageBucket: 'justgoproject-71919.appspot.com',
    iosBundleId: 'com.example.loginSignup.RunnerTests',
  );
}
